"""Init models including Students

Revision ID: 874d59875fa5
Revises: 
Create Date: 2026-04-22 19:03:37.225012

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '874d59875fa5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP INDEX IF EXISTS ix_assignment_history_id;")
    op.execute("DROP TABLE IF EXISTS assignment_history CASCADE;")
    op.alter_column('meeting_programs', 'payload',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False)
    op.alter_column('meeting_programs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_meeting_programs_id'), 'meeting_programs', ['id'], unique=False)
    op.alter_column('meeting_programs_staging', 'payload',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False)
    op.create_index(op.f('ix_meeting_programs_staging_id'), 'meeting_programs_staging', ['id'], unique=False)
    op.alter_column('students', 'infoadd',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('students', 'telefono',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('students', 'gender',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('students', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.create_unique_constraint(None, 'students', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'students', type_='unique')
    op.alter_column('students', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('students', 'gender',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('students', 'telefono',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    op.alter_column('students', 'infoadd',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.drop_index(op.f('ix_meeting_programs_staging_id'), table_name='meeting_programs_staging')
    op.alter_column('meeting_programs_staging', 'payload',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
    op.drop_index(op.f('ix_meeting_programs_id'), table_name='meeting_programs')
    op.alter_column('meeting_programs', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('meeting_programs', 'payload',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
    op.create_table('assignment_history',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('student1_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('student2_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('date_assigned', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('program_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['program_id'], ['meeting_programs.id'], name=op.f('assignment_history_program_id_fkey')),
    sa.ForeignKeyConstraint(['student1_id'], ['students.id'], name=op.f('assignment_history_student1_id_fkey')),
    sa.ForeignKeyConstraint(['student2_id'], ['students.id'], name=op.f('assignment_history_student2_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('assignment_history_pkey'))
    )
    op.create_index(op.f('ix_assignment_history_id'), 'assignment_history', ['id'], unique=False)
    # ### end Alembic commands ###
