"""add student permissions correctly

Revision ID: e0ba195c73fb
Revises: 20260424_0010
Create Date: 2026-04-24 15:49:13.643435

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0ba195c73fb'
down_revision: Union[str, Sequence[str], None] = '20260424_0010'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('aseo', sa.Boolean(), nullable=True))
    op.add_column('students', sa.Column('acomodador', sa.Boolean(), nullable=True))
    op.add_column('students', sa.Column('microfonos', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'microfonos')
    op.drop_column('students', 'acomodador')
    op.drop_column('students', 'aseo')
    # ### end Alembic commands ###
